"""
evaluate_and_shap.py

Evaluates the fine-tuned BEHRT model (T2D prediction) on the full test set
AND on the 4 horizon-censored test sets generated by
1preprocessing/04_generate_horizon_test_sets.py (5y / 3y / 2y / 1y).

For each horizon:
  1. Computes metrics: ROC-AUC, F1, Precision, Recall, Specificity,
     confusion matrix.
  2. Computes SHAP at the clinical-code level (which codes push the
     prediction towards "diabetic"), aggregated over a sample of patients.

Outputs (in OUTPUT_DIR):
  - metrics_by_horizon.csv          <- comparison table across 5y/3y/2y/1y/full
  - confusion_matrix_<horizon>.png
  - shap_top_codes_<horizon>.csv
  - shap_top_codes_<horizon>.png

Requirements:
    pip install shap --break-system-packages   (in addition to what you
    already use: torch, pytorch_pretrained_bert, scikit-learn, matplotlib,
    seaborn, duckdb)

NOTE ON THE SHAP DESIGN HERE:
shap.GradientExplainer is used over the input EMBEDDINGS (not over the
discrete input_ids, because SHAP needs a continuous, differentiable space to
perturb). age_ids, seg_ids and attention_mask are kept FIXED to each
patient's real values (not perturbed) -- only "which active code tokens push
the prediction" is explained, using the embedding of the PAD token as the
baseline (equivalent to "code absent"). This is the standard approach for
SHAP-style interpretability on BERT/EHR models.
"""

import os
import pickle
import numpy as np
import pandas as pd
import duckdb
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from sklearn.metrics import (
    roc_auc_score, f1_score, precision_score, recall_score, confusion_matrix
)
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns

# ============================================================================
# CONFIG -- absolute Google Drive paths, matching
# diabetes_fine_tuning_balanced.ipynb's convention
# ============================================================================
BEHRT_ROOT = "/content/drive/MyDrive/Colab Notebooks/BEHRT"
DATA_DIR = os.path.join(BEHRT_ROOT, "0data")
VOCAB_PATH = os.path.join(DATA_DIR, "vocab.pkl")
MODEL_WEIGHTS_PATH = os.path.join(BEHRT_ROOT, "saved_models", "balanced_diabetes_model_epoch_4.pth")  # <- adjust to your best checkpoint
OUTPUT_DIR = os.path.join(BEHRT_ROOT, "results", "evaluation")

MAX_SEQ_LENGTH = 300
BATCH_SIZE = 32
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Horizon -> test file. 'full' is the original test set (no extra horizon
# censoring), as produced by 03_train_and_test_split.py.
TEST_SETS = {
    "full": os.path.join(DATA_DIR, "diabetes_test.parquet"),
    "5y": os.path.join(DATA_DIR, "diabetes_test_5y.parquet"),
    "3y": os.path.join(DATA_DIR, "diabetes_test_3y.parquet"),
    "2y": os.path.join(DATA_DIR, "diabetes_test_2y.parquet"),
    "1y": os.path.join(DATA_DIR, "diabetes_test_1y.parquet"),
}

# How many patients to sample per horizon for SHAP (DeepExplainer/Gradient
# is expensive; no need to run all patients, 100-300 already gives a stable
# importance ranking).
SHAP_N_PATIENTS = 150
SHAP_N_BACKGROUND = 8  # copies of the PAD baseline used as reference
SHAP_TOP_K = 20

os.makedirs(OUTPUT_DIR, exist_ok=True)


# ============================================================================
# 0. Safe parquet reading (DuckDB instead of plain pandas)
# ============================================================================
def read_parquet_safe(path):
    """Plain pd.read_parquet() can throw
    'ArrowNotImplementedError: Nested data conversions not implemented for
    chunked array outputs' on parquet files with large list-type columns
    (our 'code'/'age' sequences -- some patients have 200k+ tokens). DuckDB
    reads and converts these to pandas without hitting that limitation."""
    con = duckdb.connect()
    return con.execute(f"SELECT * FROM read_parquet('{path}')").df()


# ============================================================================
# 1. VOCABULARY
# ============================================================================
def load_vocab(path):
    print(f"Loading vocabulary from {path} ...")
    with open(path, "rb") as f:
        vocab_obj = pickle.load(f)
    word2idx = vocab_obj["token2idx"] if isinstance(vocab_obj, dict) and "token2idx" in vocab_obj else vocab_obj
    idx2word = {v: k for k, v in word2idx.items()}
    print(f"  Vocab size: {len(word2idx)}")
    return word2idx, idx2word


# ============================================================================
# 2. DATASET (identical to the one used in
#    3finetuning/diabetes_fine_tuning_balanced.ipynb so the checkpoint loads
#    without surprises)
# ============================================================================
class BEHRT_Diabetes_Dataset(Dataset):
    def __init__(self, filepath, word2idx, max_len=300):
        print(f"Reading parquet file: {filepath} ...")
        self.df = read_parquet_safe(filepath)
        self.word2idx = word2idx
        self.vocab_size = len(word2idx)
        self.max_len = max_len
        self.sep_id = self.word2idx.get("SEP", 0)

    def __len__(self):
        return len(self.df)

    def _encode(self, idx):
        row = self.df.iloc[idx]
        # NOTE: when self.df was loaded via DuckDB, list-type columns come
        # back as numpy.ndarray, not plain Python lists. `array + [...]`
        # triggers numpy broadcasting (element-wise) instead of
        # concatenation, which crashes when shapes don't match. Casting to
        # list() here makes '+' behave as normal list concatenation
        # everywhere downstream (here and in raw_codes()).
        codes = list(row["code"])
        ages = list(row["age"]) if "age" in self.df.columns else [0] * len(codes)
        label = row["label"]

        if len(codes) > self.max_len:
            codes = codes[-self.max_len:]
            ages = ages[-self.max_len:]

        input_ids = [min(self.word2idx.get(c, 0), self.vocab_size - 1) for c in codes]
        age_ids = [min(int(a) if str(a).isdigit() else 0, 1321) for a in ages]

        seg_ids = []
        current_seg = 0
        for code_id in input_ids:
            seg_ids.append(current_seg)
            if code_id == self.sep_id:
                current_seg = 1 - current_seg

        attention_mask = [1] * len(input_ids)

        padding_length = self.max_len - len(input_ids)
        if padding_length > 0:
            input_ids = input_ids + [0] * padding_length
            age_ids = age_ids + [0] * padding_length
            seg_ids = seg_ids + [0] * padding_length
            attention_mask = attention_mask + [0] * padding_length

        return input_ids, age_ids, seg_ids, attention_mask, label, codes

    def __getitem__(self, idx):
        input_ids, age_ids, seg_ids, attention_mask, label, _ = self._encode(idx)
        return {
            "input_ids": torch.tensor(input_ids, dtype=torch.long),
            "age_ids": torch.tensor(age_ids, dtype=torch.long),
            "seg_ids": torch.tensor(seg_ids, dtype=torch.long),
            "attention_mask": torch.tensor(attention_mask, dtype=torch.long),
            "label": torch.tensor(label, dtype=torch.float),
        }

    def raw_codes(self, idx):
        """Returns the original (truncated/padded) code list for patient
        idx -- used to map SHAP positions back to readable code names.
        NOTE: 'PAD' (no brackets) matches this repo's vocabulary convention
        (see dataLoader/utils.py -- unbracketed special tokens)."""
        input_ids, age_ids, seg_ids, attention_mask, label, codes = self._encode(idx)
        padded_codes = codes + ["PAD"] * (self.max_len - len(codes))
        return padded_codes[: self.max_len]


# ============================================================================
# 3. MODEL (identical to the fine-tuning notebook's)
# ============================================================================
def build_model(vocab_size):
    from pytorch_pretrained_bert import BertConfig, BertModel

    class BEHRTForSequenceClassification(nn.Module):
        def __init__(self, config, num_labels):
            super().__init__()
            self.bert = BertModel(config)
            self.bert.embeddings.age_embeddings = nn.Embedding(1322, config.hidden_size)
            self.dropout = nn.Dropout(config.hidden_dropout_prob)
            self.classifier = nn.Linear(config.hidden_size, num_labels)

        def forward(self, input_ids, age_ids, seg_ids, attention_mask):
            inputs_embeds = self.bert.embeddings.word_embeddings(input_ids)
            return self.forward_from_embeds(inputs_embeds, age_ids, seg_ids, attention_mask)

        def forward_from_embeds(self, inputs_embeds, age_ids, seg_ids, attention_mask):
            """Same as forward(), but starting directly from word embeddings.
            This is the entry point SHAP will use."""
            seq_len = inputs_embeds.size(1)
            position_embeds = self.bert.embeddings.position_embeddings(
                torch.arange(seq_len, device=inputs_embeds.device).unsqueeze(0)
            )
            token_type_embeds = self.bert.embeddings.token_type_embeddings(seg_ids)
            age_embeds = self.bert.embeddings.age_embeddings(age_ids)

            embeddings = inputs_embeds + position_embeds + token_type_embeds + age_embeds
            embeddings = self.bert.embeddings.LayerNorm(embeddings)
            embeddings = self.bert.embeddings.dropout(embeddings)

            encoder_output = self.bert.encoder(embeddings, attention_mask.unsqueeze(1).unsqueeze(2))
            sequence_output = encoder_output[0] if isinstance(encoder_output, tuple) else encoder_output
            final_layer = sequence_output[-1] if isinstance(sequence_output, list) else sequence_output

            pooled_output = self.bert.pooler(final_layer)
            pooled_output = self.dropout(pooled_output)
            return self.classifier(pooled_output)

    config = BertConfig(
        vocab_size_or_config_json_file=vocab_size,
        hidden_size=288, num_hidden_layers=6, num_attention_heads=12,
        intermediate_size=512, hidden_act="gelu", hidden_dropout_prob=0.1,
        attention_probs_dropout_prob=0.1,
        max_position_embeddings=300,  # must match pretraining max_seq_len=300, NOT 512
    )
    model = BEHRTForSequenceClassification(config, num_labels=1)

    if os.path.exists(MODEL_WEIGHTS_PATH):
        print(f"Loading fine-tuned weights from {MODEL_WEIGHTS_PATH} ...")
        state_dict = torch.load(MODEL_WEIGHTS_PATH, map_location=DEVICE)
        model.load_state_dict(state_dict, strict=False)
    else:
        print(f"  WARNING: {MODEL_WEIGHTS_PATH} not found -- using randomly "
              f"initialized weights (fine for a dry run, NOT for real results).")

    model.to(DEVICE)
    model.eval()
    return model


# ============================================================================
# 4. METRICS
# ============================================================================
def evaluate_dataset(model, dataset, horizon_name):
    loader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=False)
    all_probs, all_labels = [], []

    with torch.no_grad():
        for batch in loader:
            input_ids = batch["input_ids"].to(DEVICE)
            age_ids = batch["age_ids"].to(DEVICE)
            seg_ids = batch["seg_ids"].to(DEVICE)
            mask = batch["attention_mask"].to(DEVICE)
            labels = batch["label"].cpu().numpy()

            logits = model(input_ids, age_ids=age_ids, seg_ids=seg_ids, attention_mask=mask)
            logits = logits.squeeze(-1)
            probs = torch.sigmoid(logits).cpu().numpy()

            all_probs.extend(probs)
            all_labels.extend(labels)

    all_probs = np.array(all_probs)
    all_labels = np.array(all_labels)
    all_preds = (all_probs > 0.5).astype(int)

    n_pos, n_neg = int(all_labels.sum()), int(len(all_labels) - all_labels.sum())
    if n_pos == 0 or n_neg == 0:
        print(f"  [{horizon_name}] WARNING: only one class present "
              f"({n_pos} pos / {n_neg} neg) -- AUC/metrics undefined, skipping.")
        return None

    cm = confusion_matrix(all_labels, all_preds)
    TN, FP, FN, TP = cm.ravel()
    specificity = TN / (TN + FP) if (TN + FP) > 0 else np.nan

    metrics = {
        "horizon": horizon_name,
        "n_patients": len(all_labels),
        "n_cases": n_pos,
        "n_controls": n_neg,
        "roc_auc": roc_auc_score(all_labels, all_probs),
        "f1": f1_score(all_labels, all_preds),
        "precision": precision_score(all_labels, all_preds),
        "recall": recall_score(all_labels, all_preds),
        "specificity": specificity,
    }

    plt.figure(figsize=(6, 5))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
                xticklabels=["Pred. Healthy (0)", "Pred. Diabetic (1)"],
                yticklabels=["True Healthy (0)", "True Diabetic (1)"])
    plt.title(f"Confusion Matrix - {horizon_name}")
    plt.xlabel("Model Prediction")
    plt.ylabel("Actual")
    plt.tight_layout()
    plt.savefig(os.path.join(OUTPUT_DIR, f"confusion_matrix_{horizon_name}.png"), dpi=200)
    plt.close()

    return metrics


# ============================================================================
# 5. SHAP at the clinical-code level
# ============================================================================
class EmbeddingForwardWrapper(nn.Module):
    """Wraps the model so SHAP only needs to perturb `inputs_embeds`;
    age_ids/seg_ids/attention_mask stay fixed (frozen in the constructor,
    one per patient being explained)."""

    def __init__(self, behrt_model, age_ids, seg_ids, attention_mask):
        super().__init__()
        self.behrt_model = behrt_model
        self.age_ids = age_ids
        self.seg_ids = seg_ids
        self.attention_mask = attention_mask

    def forward(self, inputs_embeds):
        batch = inputs_embeds.size(0)
        age_ids = self.age_ids.expand(batch, -1)
        seg_ids = self.seg_ids.expand(batch, -1)
        attention_mask = self.attention_mask.expand(batch, -1)
        logits = self.behrt_model.forward_from_embeds(inputs_embeds, age_ids, seg_ids, attention_mask)
        return torch.sigmoid(logits)


def compute_shap_for_horizon(model, dataset, word2idx, idx2word, horizon_name,
                              n_patients=SHAP_N_PATIENTS, n_background=SHAP_N_BACKGROUND):
    try:
        import shap
    except ImportError:
        print("  shap is not installed. Run: pip install shap --break-system-packages")
        return None

    print(f"  Running SHAP for horizon '{horizon_name}' "
          f"(sampling up to {n_patients} patients)...")

    word_embeddings = model.bert.embeddings.word_embeddings
    pad_id = word2idx.get("PAD", 0)

    n = min(n_patients, len(dataset))
    if n == 0:
        print(f"  [{horizon_name}] Empty dataset, skipping SHAP.")
        return None
    rng = np.random.default_rng(42)
    sample_idx = rng.choice(len(dataset), size=n, replace=False)

    code_shap_values = {}  # code -> list of signed SHAP contributions

    for i in sample_idx:
        item = dataset[i]
        raw_codes = dataset.raw_codes(i)

        input_ids = item["input_ids"].unsqueeze(0).to(DEVICE)
        age_ids = item["age_ids"].unsqueeze(0).to(DEVICE)
        seg_ids = item["seg_ids"].unsqueeze(0).to(DEVICE)
        attention_mask = item["attention_mask"].unsqueeze(0).to(DEVICE)

        with torch.no_grad():
            inputs_embeds = word_embeddings(input_ids)  # (1, seq_len, hidden)
            pad_embed = word_embeddings(
                torch.tensor([[pad_id]], device=DEVICE)
            ).squeeze(0)  # (1, hidden)

        # Baseline: the PAD token's embedding repeated across the whole
        # sequence, with a tiny bit of noise so GradientExplainer has
        # several reference samples (expected gradients).
        background = pad_embed.unsqueeze(0).expand(
            n_background, inputs_embeds.size(1), -1
        ).clone()
        background = background + 1e-6 * torch.randn_like(background)

        wrapper = EmbeddingForwardWrapper(model, age_ids, seg_ids, attention_mask).to(DEVICE)
        wrapper.eval()

        explainer = shap.GradientExplainer(wrapper, background)
        shap_values = explainer.shap_values(inputs_embeds, nsamples=50)

        # shap_values: (1, seq_len, hidden) for a scalar output (num_labels=1)
        sv = shap_values[0] if isinstance(shap_values, list) else shap_values
        sv = np.array(sv).reshape(inputs_embeds.size(1), -1)  # (seq_len, hidden)
        token_importance = sv.sum(axis=1)  # (seq_len,) -- contribution per position

        for pos, code in enumerate(raw_codes):
            if code in ("PAD", "SEP"):
                continue
            code_shap_values.setdefault(code, []).append(float(token_importance[pos]))

    if not code_shap_values:
        print(f"  [{horizon_name}] No SHAP values collected.")
        return None

    rows = []
    for code, vals in code_shap_values.items():
        vals = np.array(vals)
        rows.append({
            "code": code,
            "mean_shap": vals.mean(),
            "mean_abs_shap": np.abs(vals).mean(),
            "n_occurrences": len(vals),
        })
    shap_df = pd.DataFrame(rows).sort_values("mean_abs_shap", ascending=False)
    shap_df.to_csv(os.path.join(OUTPUT_DIR, f"shap_top_codes_{horizon_name}.csv"), index=False)

    top = shap_df.head(SHAP_TOP_K).iloc[::-1]
    plt.figure(figsize=(8, max(4, 0.35 * len(top))))
    colors = ["#d62728" if v > 0 else "#1f77b4" for v in top["mean_shap"]]
    plt.barh(top["code"], top["mean_shap"], color=colors)
    plt.xlabel("Mean SHAP value (-> diabetic risk)")
    plt.title(f"Top {SHAP_TOP_K} codes by |SHAP| -- horizon: {horizon_name}")
    plt.tight_layout()
    plt.savefig(os.path.join(OUTPUT_DIR, f"shap_top_codes_{horizon_name}.png"), dpi=200)
    plt.close()

    print(f"  [{horizon_name}] SHAP done. Top code: "
          f"{shap_df.iloc[0]['code']} (mean_abs_shap={shap_df.iloc[0]['mean_abs_shap']:.4f})")
    return shap_df


# ============================================================================
# MAIN
# ============================================================================
def main():
    word2idx, idx2word = load_vocab(VOCAB_PATH)
    model = build_model(vocab_size=len(word2idx))

    all_metrics = []
    for horizon_name, path in TEST_SETS.items():
        if not os.path.exists(path):
            print(f"[{horizon_name}] File not found: {path} -- skipping.")
            continue

        print(f"\n=== Horizon: {horizon_name} ===")
        dataset = BEHRT_Diabetes_Dataset(path, word2idx, MAX_SEQ_LENGTH)

        metrics = evaluate_dataset(model, dataset, horizon_name)
        if metrics is not None:
            all_metrics.append(metrics)
            print(f"  AUC={metrics['roc_auc']:.4f}  F1={metrics['f1']:.4f}  "
                  f"Prec={metrics['precision']:.4f}  Rec={metrics['recall']:.4f}  "
                  f"Spec={metrics['specificity']:.4f}  (n={metrics['n_patients']})")

        compute_shap_for_horizon(model, dataset, word2idx, idx2word, horizon_name)

    if all_metrics:
        metrics_df = pd.DataFrame(all_metrics)
        metrics_path = os.path.join(OUTPUT_DIR, "metrics_by_horizon.csv")
        metrics_df.to_csv(metrics_path, index=False)
        print(f"\nSaved comparison table -> {metrics_path}")
        print(metrics_df.to_string(index=False))

    print(f"\nAll outputs saved in: {OUTPUT_DIR}")


if __name__ == "__main__":
    main()